### ISSUE TITLE
Wrong package name

### ISSUE THREAD

**Issue by lakesare** [leanprover/reservoir#48] opened 2024-08-23 07:57 UTC
Hi!

Paperprooof is displayed as `"examples"` on https://reservoir.lean-lang.org/@Paper-Proof/examples.

I believe this happens because at one point the package in `lakefile.lean` was named `"examples"` ([link](https://github.com/Paper-Proof/paperproof/commit/54f9b362b0cb142d44bd5d785a62177ea11e95a8)). We changed it to `"paperproof"` a few months ago, however reservoir's index never got updated.

Should Paperproof take some action to fix the title?

**Comment by tydeu** [comment] 2024-08-23 17:29
@lakesare The problem is that the [`lake-manifest.json`](https://github.com/Paper-Proof/paperproof/blob/47cc2cd1f2891406128cf89bb2e3051480a3010f/lake-manifest.json#L73) of Paperproof stills names the package `examples`. Reservoir currently gets the package name from the manifest not the lakefile.

**Comment by lakesare** [comment] 2024-09-07 19:14
I don't think it helped 🤔 
Reservoir was recently reindexed, but it's still named "examples".

**Comment by tydeu** [comment] 2024-09-08 03:09
@lakesare Sorry, that's a Reservoir bug. You did fix it; Reservoir's renaming procedure is just currently broken. It will be fixed in a new version of Reservoir which is planned to go live on Monday (#45).

**Closed** 2024-09-15 22:04 UTC
Labels: C-question
